using System.Globalization;
using DomainCopilot.Application.Adjudication;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace DomainCopilot.Infrastructure.Adjudication;

/// <summary>
/// T6's document-out half: the adjudication work product an adjuster reviews, built from the same
/// typed stage records the agents themselves produced (ADR-0011) -- never a re-derived summary,
/// and never a number this document computes itself (any payout figure it prints came from
/// <see cref="Recommendation.PayoutAmount"/>, itself only ever set by a deterministic calculator
/// per ADR-0006).
///
/// A memo can be requested for a case at any point, not only once fully decided -- each section
/// renders "Not yet completed" for a stage that hasn't run rather than assuming the case reached
/// a recommendation, since (per ADR-0009) not every real run does.
/// </summary>
public sealed class AdjudicationMemoGenerator : IAdjudicationMemoGenerator
{
    static AdjudicationMemoGenerator()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public byte[] Generate(AdjudicationMemoData data)
    {
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.DefaultTextStyle(x => x.FontSize(10));

                page.Header().Column(header =>
                {
                    header.Item().Text("Adjudication Memo").FontSize(20).Bold();
                    header.Item().Text($"Meridian Mutual Insurance Company — generated {DateTimeOffset.UtcNow:yyyy-MM-dd HH:mm} UTC")
                        .FontSize(8).FontColor(Colors.Grey.Darken1);
                });

                page.Content().PaddingVertical(10).Column(column =>
                {
                    column.Spacing(12);
                    column.Item().Element(c => ComposeSummary(c, data));
                    column.Item().Element(c => ComposeCoverageSection(c, data.CoverageMatch));
                    column.Item().Element(c => ComposeAnomalySection(c, data.AnomalyFindings));
                    column.Item().Element(c => ComposeExclusionSection(c, data.ExclusionAnalysis));
                    column.Item().Element(c => ComposeRecommendationSection(c, data.Recommendation));
                    column.Item().Element(c => ComposeDecisionSection(c, data.Case));
                });

                page.Footer().AlignCenter().Text(x =>
                {
                    x.Span("Generated by Domain Copilot — this memo summarizes an AI-assisted review; the recommendation is not final until an adjuster approves it. Page ");
                    x.CurrentPageNumber();
                    x.Span(" of ");
                    x.TotalPages();
                });
            });
        });

        return document.GeneratePdf();
    }

    private static void ComposeSummary(IContainer container, AdjudicationMemoData data)
    {
        container.Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.RelativeColumn();
                columns.RelativeColumn();
            });

            AddRow(table, "Claim number", data.Case.ClaimNumber);
            AddRow(table, "Policy number", data.Case.PolicyNumber);
            AddRow(table, "Date of loss", data.Case.DateOfLoss.ToString("yyyy-MM-dd"));
            AddRow(table, "Status", data.Case.Status.ToString());
        });
    }

    private static void ComposeCoverageSection(IContainer container, CoverageMatchResult? coverageMatch)
    {
        container.Column(column =>
        {
            column.Item().Text("1. Coverage Match").Bold().FontSize(13);

            if (coverageMatch is null)
            {
                column.Item().Text("Not yet completed.").Italic().FontColor(Colors.Grey.Darken1);
                return;
            }

            column.Item().Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(2);
                    columns.RelativeColumn();
                    columns.RelativeColumn();
                    columns.RelativeColumn();
                });

                table.Header(header =>
                {
                    HeaderCell(header, "Coverage part");
                    HeaderCell(header, "Selected");
                    HeaderCell(header, "Limit");
                    HeaderCell(header, "Deductible");
                });

                BodyCell(table, coverageMatch.CoveragePart);
                BodyCell(table, coverageMatch.CoveragePartSelected ? "Yes" : "No");
                BodyCell(table, FormatUsd(coverageMatch.ApplicableLimit));
                BodyCell(table, FormatUsd(coverageMatch.ApplicableDeductible));
            });

            column.Item().PaddingTop(4).Text($"Form version: {coverageMatch.FormVersion} (effective {coverageMatch.FormVersionEffectiveDate:yyyy-MM-dd})");
            column.Item().Text($"Endorsements held: {(coverageMatch.EndorsementsHeld.Count > 0 ? string.Join(", ", coverageMatch.EndorsementsHeld) : "none")}");

            if (!string.IsNullOrWhiteSpace(coverageMatch.Notes))
            {
                column.Item().Text($"Notes: {coverageMatch.Notes}");
            }

            ComposeCitations(column, coverageMatch.Citations);
        });
    }

    private static void ComposeAnomalySection(IContainer container, AnomalyFindings? anomalyFindings)
    {
        container.Column(column =>
        {
            column.Item().Text("2. Anomaly Analysis").Bold().FontSize(13);

            if (anomalyFindings is null)
            {
                column.Item().Text("Not yet completed.").Italic().FontColor(Colors.Grey.Darken1);
                return;
            }

            column.Item().Text(anomalyFindings.Summary);

            var flags = new List<string>();
            if (anomalyFindings.DamageToValueRatioExceeds60Percent) flags.Add("Damage/value ratio exceeds 60%");
            if (anomalyFindings.DuplicateClaimsWithin90Days) flags.Add($"Duplicate claims within 90 days ({string.Join(", ", anomalyFindings.DuplicateClaimNumbers)})");
            if (anomalyFindings.DateOfLossBeforePolicyEffectiveDate) flags.Add("Date of loss precedes policy effective date");
            if (anomalyFindings.NarrativePoliceReportMismatch) flags.Add("Narrative/police report mismatch");
            if (anomalyFindings.GigEconomyUseMentioned) flags.Add($"Gig-economy use mentioned (endorsement held: {(anomalyFindings.GigEconomyEndorsementPresent ? "yes" : "no")})");

            column.Item().Text(flags.Count > 0 ? $"Flags raised: {string.Join("; ", flags)}" : "No anomaly indicators fired.");
            ComposeCitations(column, anomalyFindings.Citations);
        });
    }

    private static void ComposeExclusionSection(IContainer container, ExclusionAnalysisResult? exclusionAnalysis)
    {
        container.Column(column =>
        {
            column.Item().Text("3. Exclusion Analysis").Bold().FontSize(13);

            if (exclusionAnalysis is null)
            {
                column.Item().Text("Not yet completed.").Italic().FontColor(Colors.Grey.Darken1);
                return;
            }

            column.Item().Text(exclusionAnalysis.Reasoning);
            column.Item().Text(
                exclusionAnalysis.InsufficientInformation
                    ? "Insufficient information to confirm or rule out an exclusion."
                    : exclusionAnalysis.ExclusionsApply
                        ? $"Applicable exclusions: {string.Join(", ", exclusionAnalysis.ApplicableExclusions)}"
                        : "No exclusions apply.");
            ComposeCitations(column, exclusionAnalysis.Citations);
        });
    }

    private static void ComposeRecommendationSection(IContainer container, Recommendation? recommendation)
    {
        container.Column(column =>
        {
            column.Item().Text("4. Recommendation").Bold().FontSize(13);

            if (recommendation is null)
            {
                column.Item().Text("Not yet completed.").Italic().FontColor(Colors.Grey.Darken1);
                return;
            }

            column.Item().Background(Colors.Blue.Lighten5).Padding(8).Column(inner =>
            {
                inner.Item().Text($"Recommendation: {recommendation.RecommendationType}").Bold();
                if (recommendation.PayoutAmount is { } amount)
                {
                    inner.Item().Text($"Payout amount: {FormatUsd(amount)}" + (recommendation.PayoutToolUsed is { } tool ? $" (via {tool})" : ""));
                }

                inner.Item().Text(recommendation.Summary);
            });

            ComposeCitations(column, recommendation.Citations);
        });
    }

    private static void ComposeDecisionSection(IContainer container, Domain.Adjudication.AdjudicationCase adjudicationCase)
    {
        if (adjudicationCase.ApprovedBy is null && adjudicationCase.FailureReason is null)
        {
            return;
        }

        container.Column(column =>
        {
            column.Item().Text("5. Adjuster Decision").Bold().FontSize(13);

            if (adjudicationCase.FailureReason is not null)
            {
                column.Item().Background(Colors.Red.Lighten5).Padding(8)
                    .Text(adjudicationCase.FailureReason).FontColor(Colors.Red.Darken2);
            }

            if (adjudicationCase.ApprovedBy is not null)
            {
                column.Item().Text($"{adjudicationCase.Status} by {adjudicationCase.ApprovedBy} at {adjudicationCase.ApprovedAtUtc:yyyy-MM-dd HH:mm} UTC");
                if (!string.IsNullOrWhiteSpace(adjudicationCase.AdjusterComments))
                {
                    column.Item().Text($"Comments: {adjudicationCase.AdjusterComments}");
                }
            }
        });
    }

    private static void ComposeCitations(ColumnDescriptor column, IReadOnlyList<string> citations)
    {
        if (citations.Count == 0)
        {
            return;
        }

        column.Item().PaddingTop(2).Text("Citations:").FontSize(9).Italic();
        foreach (var citation in citations)
        {
            column.Item().Text($"• {citation}").FontSize(9).FontColor(Colors.Grey.Darken1);
        }
    }

    private static void AddRow(TableDescriptor table, string label, string value)
    {
        table.Cell().Text(label).Bold();
        table.Cell().Text(value);
    }

    private static void HeaderCell(TableCellDescriptor header, string text) =>
        header.Cell().Background(Colors.Grey.Lighten3).Padding(4).Text(text).Bold();

    private static void BodyCell(TableDescriptor table, string text) =>
        table.Cell().Padding(4).Text(text);

    // Found via a real CI failure, not assumed: decimal.ToString("C") formats using the current
    // thread's culture, which differed between this dev machine (produced "$4,500.00") and the
    // GitHub Actions runner (produced something else, failing a test asserting on the exact
    // string). This corpus is entirely USD, regardless of which machine renders the memo, so the
    // format is pinned explicitly rather than left to whatever culture happens to be active.
    private static string FormatUsd(decimal? amount) =>
        amount is { } value ? $"${value.ToString("N2", CultureInfo.InvariantCulture)}" : "—";
}
