using System.Text.RegularExpressions;
using DomainCopilot.Application.Ingestion;
using UglyToad.PdfPig;
using UglyToad.PdfPig.DocumentLayoutAnalysis.TextExtractor;

namespace DomainCopilot.Infrastructure.Ingestion;

/// <summary>
/// PDF extraction for the knowledge corpus (ADR-0004). Heading detection is pattern-based against
/// this corpus's own known numbering conventions ("Section N —", "N.N ", "N. ", "Q:", "Scenario N",
/// "Step N"), not a general-purpose layout parser — these PDFs are all generated by our own
/// Markdown -> DOCX -> LibreOffice pipeline (<c>seed-data/generate/</c>), so the conventions are
/// known in advance. <see cref="ContentOrderTextExtractor"/> is used for its correct reading-order
/// line reconstruction; word-level bounding-box grouping was tried first and discarded — it
/// scrambled word order on real output from this pipeline (verified, not assumed).
///
/// Known limitation: PdfPig's line-level text has no reliable signal for "paragraph break" vs.
/// "line wrapped mid-paragraph" (both look identical — consecutive lines, no blank line). Each
/// extracted line is therefore treated as its own chunking unit rather than true paragraphs; this
/// only affects where an oversized section's chunk boundaries fall, not what content survives.
/// </summary>
public sealed partial class PdfKnowledgeExtractor
{
    public Task<ExtractedDocument> ExtractAsync(Stream content, CancellationToken cancellationToken = default)
    {
        using var document = PdfDocument.Open(content);
        var sections = new List<ExtractedSection>();

        string currentHeading = string.Empty;
        int? currentHeadingPage = null;
        var bodyLines = new List<string>();

        void Flush()
        {
            if (currentHeading.Length == 0 && bodyLines.Count == 0)
            {
                return;
            }

            sections.Add(new ExtractedSection(currentHeading, 1, string.Join("\n\n", bodyLines), currentHeadingPage));
            bodyLines = [];
        }

        for (var pageNumber = 1; pageNumber <= document.NumberOfPages; pageNumber++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var text = ContentOrderTextExtractor.GetText(document.GetPage(pageNumber));

            foreach (var rawLine in text.Split('\n'))
            {
                var line = rawLine.Trim();
                if (line.Length == 0)
                {
                    continue;
                }

                if (HeadingPattern().IsMatch(line))
                {
                    Flush();
                    currentHeading = line;
                    currentHeadingPage = pageNumber;
                }
                else
                {
                    bodyLines.Add(line);
                    currentHeadingPage ??= pageNumber;
                }
            }
        }

        Flush();
        return Task.FromResult(new ExtractedDocument(sections));
    }

    [GeneratedRegex(@"^(Section\s+\d+\s*[—-]|Appendix\b|\d+\.\d+\s|\d+\.\s|Q:\s|Scenario\s+\d+|Step\s+\d+)")]
    private static partial Regex HeadingPattern();
}
